version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
      - dependency-name: 'react-native'      
      - dependency-name: 'react-test-renderer'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
